### ISSUE TITLE
Speakers update

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/200ok-site#170]
- [x] #171 Can we get there to be tabs on the side for speakers and for sponsors, so people don't have to scroll? -EH
- [x] #173 Add schedule information for each speaker. (once finalized)
- [x] #172 alt and title attributes for the speaker images and links
- [x] #172 Consistent target for Twitter and website links
- [x] #172 Increment h2/h3 to h3/h4. Also, I wouldn’t hate it if the speaker titles were title-case instead of all-caps 😉

**Comment by maxxcrawford** [comment]
-     Add schedule information for each speaker. (once finalized)
-     alt and title attributes for the speaker images and links
-     Consistent target for Twitter and website links
-     Increment h2/h3 to h3/h4. Also, I wouldn’t hate it if the speaker titles were title-case instead of all-caps 😉
