### ISSUE TITLE
2019 CFP Opening

### ISSUE THREAD

**Issue by maxxcrawford** [techlahoma/200ok-site#67]
## Tasks
- [x] Archive 2018
- [x] Update Copy Date
- [x] Update CTA to be "Submit Talk", Link to [CFP site](https://cfp.techlahoma.org/events/200ok-2019)

- [x] Hide Schedule

- [x] Hide Sponsors in each section, add "View the Sponsorship Prospectus and contact us about sponsoring.", except for Lunch / Rogue
